### PR TITLE
(WIP) Added support for tty usage of attach.

### PR DESCRIPTION
**Pull request by gilescope**
Really need your thoughts on this one. To use the tty mode of attach one needs to read the raw Response object (once a container has been created with tty=true). I've done this as a separate method so it's backward compatible.

It feels like tty containers and non-tty containers are different types... I don't think there's much we can do about that without radical surgery.

Keen to hear other ideas as to how to solve this / reduce duplication.

### CODE REVIEW

**Comment by eldesh** [comment]
The tty-attached container is branched with `/containers/create` api?
So the body of `attach_container_tty` seems to be the (almost) same to `attach_container`.

Isn't it better to change the type of the return value of `attach_container` api according to the container?

For example:
```
fn attach_container(&self, container) -> Result<...> {
  ..
  let res = ..
  if container.with_tty() {           <-- can we implement ?
    AttachWithTTYResponse::new(res)
  } else {
    AttachResponse::new(res)
  }
}
```

Or extends `AttachResponse` like:

```
enum AttachResponse {
  Multiplexed(res),
  Tty(res),
}
// and AttachContainer's fields may be Optional ... ?

if container.with_tty() {
  AttachResponse::Tty(res)
} else {
  AttachResponse::Multiplexed(res)
}
```

**Comment by gilescope** [comment]
I'm not sure there's an easy way to know if it's tty as someone else could have created the container. 

Maybe I could just make AttachResponse convertible back into() a Response?
```
/// Get raw response for attaching with tty.
impl From<AttachResponse> for Response {
    fn from(res: AttachResponse) -> Self {
        res.res
    }
}
```

**Comment by eldesh** [comment]
Thank you for your studying enum solution. 👍
As you indicated, that solution is not so good because of two calls to docker.
Further, any code using attach container API may be redundant (with unwrapping).

How about `attach_container` returns a raw response,
and a user converts the response to the correct type.

```
// a new type for TTY container response
+ pub struct TtyContainer(Response);

// disable into()
- impl From<AttachResonse> for AttachContainer ...

impl AttachResopnse {
  ..
  // choose correct type explicitly
+ fn to_attach_container(self) -> AttachContainer { .. }
+ fn to_tty_container(self) -> TtyContainer { TtyContainer(self.0) }
}

// not change from original code
fn attach_container(...) -> Result<AttachResponse> {
	..
}
```
If this idea are choosen, some code for enum solution would be reverted. I'm sorry ;(


Reguardless of what you take solution for this PR, refactoring `container_info` is preferred.
It may be as well to make the refactoring as another PR.

**Comment by gilescope** [comment]
Sorry been caught up on other things, will sort this out next.

**Comment by gilescope** [comment]
Closing this in favor of https://github.com/eldesh/dockworker/pull/43

**Pull request closed without merging**
