### PR TITLE
Add docker head file

### PR DESCRIPTION
**Pull request by idanski**
For reference:
https://docs.docker.com/engine/api/v1.40/#operation/ContainerArchiveInfo

Also more info here (find: X-Docker-Container-Path-Stat):
https://docs.docker.com/engine/api/v1.21/

### CODE REVIEW

**Comment by eldesh** [comment]
Could you add a unit test for head_file?

**Comment by idanski** [comment]
@eldesh you mean other than that I wrote?
https://github.com/eldesh/dockworker/pull/60/files#diff-088955e536a8719ce05dea2f9c99b4feR1133

**Comment by eldesh** [comment]
@idanski Oh, sorry. You wrote a test already.

**Comment by eldesh** [comment]
Thank you for your contribution!

**Pull request merged**
