### PR TITLE
fix volumes information in docker info struct (fixes: #58)

### PR DESCRIPTION
**Pull request by idanski**

### CODE REVIEW

**Comment by idanski** [comment]
hey @eldesh, 
seemingly unrelated test: `create_remove_container` has failed. 
do you know why?

**Comment by eldesh** [comment]
`hello-world:linux` image is used for `create_remove_container` too. So remove image operation conflict each other.

**Comment by eldesh** [comment]
Fixing type of `Volumes` looks good. But `container_info` is tested in `test_container_info`.

**Comment by idanski** [comment]
@eldesh Got it, thanks.
I deleted my test and updated the json fixture to have non-null 'Volumes' value instead to test my fix.

Tests are passing now. :grin:

**Comment by eldesh** [comment]
Thank you for your contribution.

**Pull request merged**
