### PR TITLE
Run unit tests sequentially in CI

### LINKED ISSUE #70: Perform unit tests sequentially
Unit test cases conflicts each other if it uses a docker image same to other case.
ref. #69

```
#[cfg(test)]
fn test () {
    let image = ...;
    test_api_0(&image);
    test_api_1(&image);
    test_api_2(&image);
    ...
}
```

### PR DESCRIPTION
**Pull request by acidghost**
closes #70

### CODE REVIEW

**Comment by acidghost** [comment]
@eldesh The build got a `SIGKILL` while compiling the crate.. Could it be me changing the PR title?

**Comment by eldesh** [comment]
`SIGKILL` caused by out of memory with parallel execution.

**Comment by eldesh** [comment]
May I close this PR?

**Comment by acidghost** [comment]
Should not `-j 0` set parallization to zero?

**Comment by acidghost** [comment]
@eldesh can you merge into master so I can merge back into PR #69?

**Comment by eldesh** [comment]
With `-j1`, independent test cases would not perform in parallel.
Please read code block in #70. Changing `-j` option would not solve #70.

**Comment by acidghost** [comment]
Turns out that `-j` option controls number of threads that cargo uses to compile the target and tests. The `--test-threads` option (passed as `cargo test -- --test-threads 1`) controls the number of threads used to run the tests.

**Comment by eldesh** [comment]
https://github.com/eldesh/dockworker/pull/71#issuecomment-548309433

**Comment by acidghost** [comment]
@eldesh The `--test-threads 1` option will prevent tests from running in parallel. Please read the cargo documentation and consider reopening this PR..

**Comment by acidghost** [comment]
@eldesh Please, read this https://doc.rust-lang.org/book/ch11-02-running-tests.html#running-tests-in-parallel-or-consecutively

**Pull request closed without merging**
